name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Build Docker Image and push it to Google Artifact Registry
        run: gcloud builds submit --tag southamerica-east1-docker.pkg.dev/plasma-line-466616-i9/notely-ar-repo/notely:1 .

      - name: Run Migrations
        run: npm run db:migrate

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image southamerica-east1-docker.pkg.dev/plasma-line-466616-i9/notely-ar-repo/notely:1 --region southamerica-east1 --allow-unauthenticated --project plasma-line-466616-i9 --max-instances=4
